details:
  namespace: student60-bookinfo-dev
  image: ghcr.io/songkran-060/bookinfo-details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.dev.opsta.net
  path: "/student60/details(/|$)(.*)"
  serviceType: ClusterIP